version: '3'
services:
  nginx:
    image: moonnz/nginx-4dvop-app
    ports:
      - "8080:8080"
  haproxy:
    image: moonnz/haproxy-4dvop-app
    ports:
      - "80:80"
    depends_on:
      - nginx
