FROM ubuntu
RUN apt update
RUN apt install -y nginx
RUN rm /var/www/html/*
COPY static-website-example/* /var/www/html/
RUN sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
EXPOSE 8080
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]

