---

- hosts: all
  become: true
  tasks:
    - name: Deploy 4dvop-nginx 
      docker_container:
        name: nginx
        hostname: nginx
        image: moonnz/nginx-4dvop-app
        state: started
        ports:
          - "8080:8080"
    - name: Deploy 4dvop-haproxy
      docker_container:
        name: haproxy
        hostname: haproxy 
        image: moonnz/haproxy-4dvop-app
        state: started
        links:  
          - nginx:nginx
        ports:
          - "80:80"
